// Pronto Food Delivery product catalog.
// Real content only: restaurant names/products are illustrative browsing UI (not grounded in
// Casey's FAQ knowledge — she doesn't know menu-level detail, see README). Blends individual
// (b2c) and bulk/catering (b2b) items per restaurant to reflect both consumer ordering and the
// real "Pronto for Business" program (group orders, per-person budgets, recurring office orders).

export const PRODUCTS = [
  {
    id: "sk-rainbow-roll",
    restaurant: "Sushi Kai",
    category: "Japanese",
    name: "Rainbow Roll Combo",
    channel: "b2c",
    price: 16.99,
    priceLabel: "$16.99",
    blurb:
      "Six-piece rainbow roll with tuna, salmon, and avocado, served with miso soup and a side salad.",
    image: "/products/pronto-rainbow-roll-meal.png",
  },
  {
    id: "sk-bento-deluxe",
    restaurant: "Sushi Kai",
    category: "Japanese",
    name: "Bento Box Deluxe",
    channel: "b2c",
    price: 18.49,
    priceLabel: "$18.49",
    blurb: "Grilled teriyaki chicken, four-piece California roll, gyoza, and steamed rice.",
    image: "/products/bento-box-deluxe.png",
  },
  {
    id: "sk-office-platter-20",
    restaurant: "Sushi Kai",
    category: "Japanese",
    name: "Office Sushi Platter, 20-pc",
    channel: "b2b",
    price: 89.99,
    priceLabel: "$89.99",
    minNote: "serves 4–6",
    blurb:
      "Chef's selection of nigiri and rolls arranged for easy sharing — a Pronto for Business favorite for client meetings.",
    image: "/products/Office-Sushi-Platter-20-pc.png",
  },
  {
    id: "sk-party-tray-50",
    restaurant: "Sushi Kai",
    category: "Japanese",
    name: "Sushi Party Tray, 50-pc",
    channel: "b2b",
    price: 189.99,
    priceLabel: "$189.99",
    minNote: "serves 10–12",
    blurb: "Our largest tray, built for all-hands events and office celebrations.",
    image: "/products/Sushi-Party-Tray-50-pc.png",
  },
  {
    id: "bi-chicken-parm",
    restaurant: "Bella Italia",
    category: "Italian",
    name: "Chicken Parmesan Classic",
    channel: "b2c",
    price: 15.49,
    priceLabel: "$15.49",
    blurb: "Breaded chicken breast, marinara, melted mozzarella, over spaghetti.",
    image: "/products/Chicken-Parmesan-Classic.png",
  },
  {
    id: "bi-margherita",
    restaurant: "Bella Italia",
    category: "Italian",
    name: "Margherita Pizza, Personal",
    channel: "b2c",
    price: 12.99,
    priceLabel: "$12.99",
    blurb: "Wood-fired crust, San Marzano tomatoes, fresh mozzarella, basil.",
    image: "/products/Margherita-Pizza-Personal.png",
  },
  {
    id: "bi-lasagna-tray",
    restaurant: "Bella Italia",
    category: "Italian",
    name: "Family Lasagna Tray",
    channel: "both",
    price: 54.99,
    priceLabel: "$54.99",
    minNote: "serves 6–8",
    blurb:
      "Baked layers of pasta, three-cheese blend, slow-simmered meat sauce — dinner or a small team lunch.",
    image: "/products/Family-Lasagna-Tray.png",
  },
  {
    id: "bi-pasta-bar",
    restaurant: "Bella Italia",
    category: "Italian",
    name: "Pasta Bar Catering",
    channel: "b2b",
    price: 12.5,
    priceLabel: "$12.50/person",
    minNote: "min 15",
    blurb:
      "Build-your-own pasta bar with two sauces, garlic bread, and Caesar salad — priced per person via the Group Order tool.",
    image: "/products/Pasta-Bar-Catering.png",
  },
  {
    id: "bs-classic-burger",
    restaurant: "The Burger Shed",
    category: "American",
    name: "Shed Classic Burger & Fries",
    channel: "b2c",
    price: 13.99,
    priceLabel: "$13.99",
    blurb: "Half-pound patty, cheddar, house sauce, hand-cut fries.",
    image: "/products/Shed-Classic-Burger-Fries.png",
  },
  {
    id: "bs-veggie-burger",
    restaurant: "The Burger Shed",
    category: "American",
    name: "Loaded Veggie Burger",
    channel: "b2c",
    price: 12.49,
    priceLabel: "$12.49",
    blurb: "Plant-based patty, avocado, sprouts, chipotle aioli.",
    image: "/products/Loaded-Veggie-Burger.png",
  },
  {
    id: "bs-burger-bar",
    restaurant: "The Burger Shed",
    category: "American",
    name: "Burger Bar Group Order",
    channel: "b2b",
    price: 14.0,
    priceLabel: "$14.00/person",
    minNote: "min 10",
    blurb:
      "Build-your-own burger station, three patty options, toppings bar — set a per-person budget through the Group Order tool.",
    image: "/products/Burger-Bar-Group-Order.png",
  },
  {
    id: "sg-butter-chicken",
    restaurant: "Spice Garden",
    category: "Indian",
    name: "Butter Chicken & Naan",
    channel: "b2c",
    price: 14.99,
    priceLabel: "$14.99",
    blurb: "Tender chicken in creamy tomato-butter sauce, garlic naan, basmati rice.",
    image: "/products/Butter-Chicken-Naan.png",
  },
  {
    id: "sg-veg-thali",
    restaurant: "Spice Garden",
    category: "Indian",
    name: "Vegetable Thali",
    channel: "b2c",
    price: 13.49,
    priceLabel: "$13.49",
    blurb: "A balanced plate of dal, seasonal vegetable curry, raita, and rice.",
    image: "/products/Vegetable-Thali.png",
  },
  {
    id: "sg-curry-trio",
    restaurant: "Spice Garden",
    category: "Indian",
    name: "Curry Catering Trio",
    channel: "b2b",
    price: 129.99,
    priceLabel: "$129.99",
    minNote: "serves 10",
    blurb:
      "Three signature curries, rice, and naan, portioned for team lunches and recurring office orders.",
    image: "/products/Curry-Catering-Trio.png",
  },
];

// Real — from the Missing & Problem Deliveries FAQ. These map to actual Report an Issue
// categories Casey can help with, unlike the product grid above.
export const HELP_TOPICS = [
  { icon: "🚫", label: "Order Never Arrived" },
  { icon: "📦", label: "Missing Item" },
  { icon: "🔄", label: "Wrong Item" },
  { icon: "🍽️", label: "Food Quality" },
  { icon: "⏰", label: "Late Delivery" },
];
